App Release 1
raminka13/premier-standings pull request #3
Opened 2022-08-31 18:38 UTC by raminka13

## Leagues Standings App v.0.1
![](https://github.com/raminka13/premier-standings/blob/dev/Seasons.png)
 - Selected the [API](https://github.com/azharimm/football-standings-api).
 - Built file structure for React app.
 - Prepared routes and navigation in-app.
 - Fetch data from the API in the reducers thunk.
 - Created the tests for the application.
 - Style your components to match the design by [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio).
 - Deployed the project to [Netlify](https://leagues-standings-raminka.netlify.app/) and tested for final details.
 - Recorded a [Video Presentation](https://youtu.be/Hy242UqNOts) for project.
 - Created a great `README` and `PR` description.

I hope you enjoy this project as much as I enjoyed coding it.
Thanks.

2022-08-31 19:05 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @raminka13👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Awsome UI design. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 19:05 UTC, thecodechaser commented on src/components/Standings.js
> +          </tr>
- [ ] Please implement a "Back" button (<) on the details page, When the user clicks on the button the user should navigate to the home page. `(I can see there's a home button on the navbar that can be used to go to the home page but this is a project requirement to implement the back button)`.
![image](https://user-images.githubusercontent.com/83803414/187758327-e2107722-04cb-42fa-bb51-6ca9ae5a6b7e.png)

2022-08-31 19:05 UTC, thecodechaser commented on src/components/Seasons.js
> +            <span className="season-display">
- [ ] Please implement the search functionality on the homepage that should filter the data, You can filter the year on the search functionality. `(For example, users can search the year 2015 in the search bar)`.
![image](https://user-images.githubusercontent.com/83803414/187759671-23ae6dfe-85dc-4b79-8718-9fa0b979c410.png)

2022-08-31 19:45 UTC, raminka13 commented on src/components/Standings.js
> +          </tr>
Instead of home button just a back button?

2022-08-31 19:45 UTC, raminka13 commented on src/components/Seasons.js
> +            <span className="season-display">
Awesome suggestion. Will do that.

2022-08-31 19:47 UTC, thecodechaser commented on src/components/Standings.js
> +          </tr>
@raminka13 Home button should be there as well

2022-09-01 13:55 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @raminka13  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 14:15 UTC, merged